In [1582]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

from sklearn.pipeline import FeatureUnion
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

train = pd.read_csv('home-data/train.csv')
test = pd.read_csv('home-data/test.csv')

combine = [train,test]

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 100)


In [1583]:
# Im ordering the columns by type (objects vs numbers) for simplicity

list_cat = []
list_num = []
for j in train.columns:
    if train[j].dtype == 'int64' or train[j].dtype == 'float64':
        list_num.append(j)
    else:
        list_cat.append(j)
        
new_order = list_cat + list_num
train = train[new_order]

new_order = new_order[0:-1]
test = test[new_order]

combine = [train,test]

In [1584]:
#Lets see how many missing data we have

print(combine[0].isnull().sum().sort_values(ascending = False))
print('---'*10)
print(combine[1].isnull().sum().sort_values(ascending = False))

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
FireplaceQu       690
LotFrontage       259
GarageCond         81
GarageQual         81
GarageFinish       81
GarageType         81
GarageYrBlt        81
BsmtFinType2       38
BsmtExposure       38
BsmtQual           37
BsmtCond           37
BsmtFinType1       37
MasVnrType          8
MasVnrArea          8
Electrical          1
MoSold              0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
2ndFlrSF            0
MiscVal             0
TotRmsAbvGrd        0
EnclosedPorch       0
TotalBsmtSF         0
BsmtUnfSF           0
BsmtFinSF2          0
BsmtFinSF1          0
YrSold              0
1stFlrSF            0
OpenPorchSF         0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
WoodDeckSF          0
YearBuilt           0
GarageArea          0
GarageCars          0
Fireplaces          0
HalfBath            0
BedroomAbv

In [1585]:
# Replace all nan with a category NAN based on the information we have 
for dataset in combine:
    dataset['PoolQC'] = dataset['PoolQC'].replace(np.nan, 'NA')
    dataset['Alley'] = dataset['Alley'].replace(np.nan, 'NA')
    dataset['Fence'] = dataset['Fence'].replace(np.nan, 'NA')
    dataset['MiscFeature'] = dataset['MiscFeature'].replace(np.nan, 'NA')
    dataset['FireplaceQu'] = dataset['FireplaceQu'].replace(np.nan, 'NA')
    dataset['GarageQual'] = dataset['GarageQual'].replace(np.nan, 'NA')
    dataset['GarageFinish'] = dataset['GarageFinish'].replace(np.nan, 'NA')
    dataset['GarageType'] = dataset['GarageType'].replace(np.nan, 'NA')
    dataset['GarageCond'] = dataset['GarageCond'].replace(np.nan, 'NA')
    dataset['BsmtCond'] = dataset['BsmtCond'].replace(np.nan, 'NA')
    dataset['BsmtExposure'] = dataset['BsmtExposure'].replace(np.nan, 'NA')
    dataset['BsmtFinType2'] = dataset['BsmtFinType2'].replace(np.nan, 'NA')
    dataset['BsmtFinType1'] = dataset['BsmtFinType1'].replace(np.nan, 'NA')
#for dataset in combine:
 #   for j in list_cat:
  #      dataset[j] = dataset[j].replace(np.nan, 'NA')    

In [1586]:
#for dataset in combine:
#    dataset.drop(['SaleCondition'],axis=1,inplace=True)
#train = train.drop(['PoolQC','Alley','Fence','FireplaceQu','MiscFeature','SaleCondition'],axis=1)
#test = test.drop(['PoolQC','Alley','Fence','FireplaceQu','MiscFeature','SaleCondition'],axis=1)

print(combine[0].isnull().sum().sort_values(ascending = False))
print('---'*10)
print(combine[1].isnull().sum().sort_values(ascending = False))

LotFrontage      259
GarageYrBlt       81
BsmtQual          37
MasVnrType         8
MasVnrArea         8
Electrical         1
BsmtUnfSF          0
GrLivArea          0
LowQualFinSF       0
2ndFlrSF           0
1stFlrSF           0
TotalBsmtSF        0
BsmtFinSF2         0
BsmtHalfBath       0
BsmtFinSF1         0
YearRemodAdd       0
YearBuilt          0
OverallCond        0
OverallQual        0
LotArea            0
MSSubClass         0
BsmtFullBath       0
MSZoning           0
SaleCondition      0
OpenPorchSF        0
YrSold             0
MoSold             0
MiscVal            0
PoolArea           0
ScreenPorch        0
3SsnPorch          0
EnclosedPorch      0
WoodDeckSF         0
FullBath           0
GarageArea         0
GarageCars         0
Fireplaces         0
TotRmsAbvGrd       0
KitchenAbvGr       0
BedroomAbvGr       0
HalfBath           0
Id                 0
MiscFeature        0
SaleType           0
Condition2         0
ExterQual          0
Exterior2nd        0
Exterior1st  

In [1587]:
combine[0].isnull().sum().sort_values(ascending = False)

LotFrontage      259
GarageYrBlt       81
BsmtQual          37
MasVnrType         8
MasVnrArea         8
Electrical         1
BsmtUnfSF          0
GrLivArea          0
LowQualFinSF       0
2ndFlrSF           0
1stFlrSF           0
TotalBsmtSF        0
BsmtFinSF2         0
BsmtHalfBath       0
BsmtFinSF1         0
YearRemodAdd       0
YearBuilt          0
OverallCond        0
OverallQual        0
LotArea            0
MSSubClass         0
BsmtFullBath       0
MSZoning           0
SaleCondition      0
OpenPorchSF        0
YrSold             0
MoSold             0
MiscVal            0
PoolArea           0
ScreenPorch        0
3SsnPorch          0
EnclosedPorch      0
WoodDeckSF         0
FullBath           0
GarageArea         0
GarageCars         0
Fireplaces         0
TotRmsAbvGrd       0
KitchenAbvGr       0
BedroomAbvGr       0
HalfBath           0
Id                 0
MiscFeature        0
SaleType           0
Condition2         0
ExterQual          0
Exterior2nd        0
Exterior1st  

In [1588]:
combine[1].isnull().sum().sort_values(ascending = False)

LotFrontage      227
GarageYrBlt       78
BsmtQual          44
MasVnrType        16
MasVnrArea        15
MSZoning           4
BsmtFullBath       2
Functional         2
Utilities          2
BsmtHalfBath       2
BsmtFinSF1         1
KitchenQual        1
SaleType           1
GarageArea         1
GarageCars         1
Exterior1st        1
Exterior2nd        1
TotalBsmtSF        1
BsmtUnfSF          1
BsmtFinSF2         1
YearBuilt          0
MoSold             0
YearRemodAdd       0
2ndFlrSF           0
OverallCond        0
OverallQual        0
LotArea            0
1stFlrSF           0
ScreenPorch        0
LowQualFinSF       0
GrLivArea          0
3SsnPorch          0
FullBath           0
MSSubClass         0
MiscVal            0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
PoolArea           0
Fireplaces         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
HalfBath           0
MiscFeature        0
Id                 0
Condition2         0
ExterCond    

In [1589]:
corr_matrix = combine[0].corr()
a = corr_matrix['SalePrice'].sort_values(ascending = False)
num_cols = a[(a > 0.6)].index.tolist()
num_cols

['SalePrice',
 'OverallQual',
 'GrLivArea',
 'GarageCars',
 'GarageArea',
 'TotalBsmtSF',
 '1stFlrSF']

In [1590]:
# The numerical data im filling with median , the categorial missing data Im gonna drop it since its
# not that many rows

for dataset in combine:
    for col in dataset.select_dtypes(exclude='object').columns:
        dataset[col].fillna(dataset[col].median(),inplace=True) 
    #print(dataset.isnull().sum().sort_values(ascending = False))
#for dataset in combine:
 #   dataset.dropna(inplace=True)



In [1591]:
X = combine[0].drop(['SalePrice'],axis=1)
y = combine[0]['SalePrice']
test = combine[1]


drop_cols = []
for dataset in combine:
    for col in dataset.select_dtypes(exclude=['int64','int32']).columns.tolist():
        if dataset[col].isnull().sum() > 0:
            drop_cols.append(col)
            

#for col in combine[0].select_dtypes(exclude=['int64','int32','float64']).columns.tolist():
   # if combine[0][col].isnull().sum() > 0:
       # drop_cols.append(col)

            
#test.drop(drop_cols,axis=1,inplace=True)
#X.drop(drop_cols,axis=1,inplace=True)

cat_cols = X.select_dtypes(exclude=['int64','int32','float64']).columns.tolist()
num_cols = X._get_numeric_data().columns
num_cols = num_cols.tolist()

In [1592]:
combine[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MSZoning       1455 non-null   object 
 1   Street         1459 non-null   object 
 2   Alley          1459 non-null   object 
 3   LotShape       1459 non-null   object 
 4   LandContour    1459 non-null   object 
 5   Utilities      1457 non-null   object 
 6   LotConfig      1459 non-null   object 
 7   LandSlope      1459 non-null   object 
 8   Neighborhood   1459 non-null   object 
 9   Condition1     1459 non-null   object 
 10  Condition2     1459 non-null   object 
 11  BldgType       1459 non-null   object 
 12  HouseStyle     1459 non-null   object 
 13  RoofStyle      1459 non-null   object 
 14  RoofMatl       1459 non-null   object 
 15  Exterior1st    1458 non-null   object 
 16  Exterior2nd    1458 non-null   object 
 17  MasVnrType     1443 non-null   object 
 18  ExterQua

In [1593]:
num_pipeline = Pipeline([
    ('std_scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
    ('OrdinalEncoder', OneHotEncoder()),
])

full_pipeline = ColumnTransformer(
    transformers=[
        ('cat', cat_pipeline, cat_cols),
        ('num', num_pipeline, num_cols)
        ]
)


#X_train = full_pipeline.fit_transform(X)
#X_test = full_pipeline.transform(test)



In [1594]:
test['FireplaceQu'].unique()

array(['NA', 'TA', 'Gd', 'Po', 'Fa', 'Ex'], dtype=object)

In [1595]:
num_pipeline = Pipeline([
    ('std_scaler', StandardScaler()),
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('OrdinalEncoder', OneHotEncoder()),
])

full_pipeline = ColumnTransformer(
    transformers=[
        ('cat', cat_pipeline, cat_cols),
        ('num', num_pipeline, num_cols)
        ]
)


X_train = full_pipeline.fit_transform(X).toarray()
X_test = full_pipeline.transform(test).toarray()

## Training and prediction

In [1596]:
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import ElasticNet
from sklearn.model_selection import cross_val_score



In [1597]:
from sklearn import decomposition

pca = decomposition.PCA(n_components=200)
#X_train = pca.fit_transform(X_train)
#X_test = pca.transform(X_test)

In [1598]:
lin_reg = LinearRegression()
lin_reg.fit(X_train,y)

scores = cross_val_score(lin_reg, X_train, y ,scoring="neg_mean_squared_error", cv=10)
lin_reg_scores = np.sqrt(-scores)
lin_reg_scores



array([3.24868166e+13, 2.95032855e+14, 6.26555815e+14, 5.01621744e+13,
       2.65502217e+14, 2.69755624e+12, 2.24133072e+15, 1.34014939e+15,
       6.03912225e+15, 1.72467573e+15])

In [1599]:
SGD = SGDRegressor()
SGD.fit(X_train,y)

scores = cross_val_score(SGD, X_train, y ,scoring="neg_mean_squared_error", cv=10)
SGD_scores = np.sqrt(-scores)
SGD_scores



array([22082.43403125, 25021.1960603 , 26143.68976445, 40344.46360143,
       33494.01923836, 25676.00891243, 25704.60416624, 24528.35676838,
       58719.34424681, 26167.79303675])

In [1600]:
from sklearn.linear_model import ElasticNet

ENet = ElasticNet(random_state=0)
ENet.fit(X_train,y)

scores = cross_val_score(ENet, X_train, y ,scoring="neg_mean_squared_error", cv=10)
ENet_scores = np.sqrt(-scores)
ENet_scores



array([23267.86918309, 29518.84590549, 24896.94788144, 39911.22050478,
       41099.39913409, 29903.32936078, 26976.33111593, 26930.854667  ,
       59502.44662097, 25088.52272089])

In [1601]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=1, solver="cholesky")
ridge_reg.fit(X_train, y)

scores = cross_val_score(ridge_reg, X_train, y ,scoring="neg_mean_squared_error", cv=10)
ridge_reg_scores = np.sqrt(-scores)
ridge_reg_scores

array([20901.89678172, 26664.97159074, 25312.6685403 , 39569.61688993,
       31349.42865955, 29687.21983277, 25641.33224567, 24276.58337748,
       62621.54382032, 24960.70202963])

In [1602]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.1)
lasso_reg.fit(X_train, y)

scores = cross_val_score(lasso_reg, X_train, y ,scoring="neg_mean_squared_error", cv=10)
lasso_reg_scores = np.sqrt(-scores)
lasso_reg_scores

array([21927.58229286, 32366.87009969, 23758.30919212, 41244.99236833,
       30343.25216338, 43331.85940908, 24123.05481569, 22709.78019622,
       68158.47482429, 33194.7228089 ])

In [1603]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

random_forest_reg = RandomForestRegressor(n_estimators=200, random_state=0)
#random_forest_reg.fit(X_train,y)

#scores = cross_val_score(random_forest_reg, X_train, y ,scoring="neg_mean_squared_error", cv=5)
#random_forest_reg_score = np.sqrt(-scores)
#random_forest_reg_score

para_grids = {
            "n_estimators" : [10,50,100],
            "max_features" : ["auto", "log2", "sqrt"],
            "bootstrap"    : [True, False]
        }


grid = GridSearchCV(random_forest_reg, para_grids)
grid.fit(X_train,y)
forest = grid.best_estimator_




RandomForestRegressor(bootstrap=False, max_features='sqrt', random_state=0)

In [1606]:
scores = cross_val_score(forest, X_train, y ,scoring="neg_mean_squared_error", cv=5)
random_forest_reg_score = np.sqrt(-scores)
random_forest_reg_score

array([24731.07776645, 33211.19732214, 34315.56512533, 22641.70417336,
       31009.40146382])

In [1608]:
models = [ridge_reg_scores,lasso_reg_scores,ENet_scores,SGD_scores,lin_reg_scores,random_forest_reg_score]
tags = ['ridge_reg_score','lasso_reg_score','ENet_score','SGD_score','lin_reg_score','random_forest_reg_score']
for j in range(0,len(models)):
    print(tags[j] + ' : ' + str((sum(models[j])/len(models[j]))))

ridge_reg_score : 31098.596376810096
lasso_reg_score : 34115.88981705705
ENet_score : 32709.5767094464
SGD_score : 30788.190982639797
lin_reg_score : 1261771552114246.0
random_forest_reg_score : 29181.789170220174


In [1605]:
predictions = random_forest_reg.predict(X_test)

output = pd.DataFrame()

output['Id'] ,output['SalePrice']= [j for j in range (1461,2920)] , predictions

output.to_csv('submit_housing', index=False)

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [1558]:
output

Id   SalePrice
0     1461  127545.830
1     1462  155243.660
2     1463  177709.240
3     1464  182672.830
4     1465  202114.630
...    ...         ...
1454  2915   84631.965
1455  2916   85981.555
1456  2917  152533.425
1457  2918  112229.060
1458  2919  224854.285

[1459 rows x 2 columns]